server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rikkeibank_customer?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
      key-prefix: "rikkeibank:"
      use-key-prefix: true
logging:
  level:
    com.rikkeibank.customer: DEBUG
